### ISSUE TITLE
车牌正则校验新能源车牌不通过

### ISSUE THREAD

**Issue by zhumengzj** [jaywcjlove/handbook#51]
![image](https://user-images.githubusercontent.com/25915202/59239613-b129b780-8c34-11e9-8ff3-10bb6c1af058.png)

**Comment by jaywcjlove** [comment]
@zhumengzj 好像多了一位

**Comment by jaywcjlove** [comment]
给你搜索了个教程，自己判断一下是否正确，可以基于这个正则改改：[正则验证车牌号码，包括新能源车牌](https://blog.csdn.net/xjun0812/article/details/81806118)

```js
/^(([京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领][A-Z](([0-9]{5}[DF])|([DF]([A-HJ-NP-Z0-9])[0-9]{4})))|([京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领][A-Z][A-HJ-NP-Z0-9]{4}[A-HJ-NP-Z0-9挂学警港澳使领]))$/.test('粤DB1008')
```

## 车牌验证规则

1. **传统车牌**

第1位为省份简称（汉字），第二位为发牌机关代号（A-Z的字母）第3到第7位为序号（由字母或数字组成，但不存在字母I和O，防止和数字1、0混淆，另外最后一位可能是“挂学警港澳使领”中的一个汉字）。

2. **新能源车牌**

第1位和第2位与传统车牌一致，第3到第8位为序号（比传统车牌多一位）。新能源车牌的序号规则如下：

- 小型车：第1位只能是字母D或F，第2为可以是数字或字母，第3到6位必须是数字。
- 大型车：第1位到第5位必须是数字，第6位只能是字母D或F。

**Comment by zhumengzj** [comment]
@jaywcjlove 不多，新能源车车牌一共八位数

**Comment by ddzzhen** [comment]
中文可以直接这样匹配吗？python2应该做不到吧

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/regexp-example

**Comment by firedemo1** [comment]
来信已收到，信已收到，已收到，收到，到....谢谢！
