### ISSUE TITLE
不知道大佬可不可以加多一些离线文档呢，比如nuxt.js

### ISSUE THREAD

**Issue by SunPm** [jaywcjlove/handbook#58]
十分感谢

**Comment by jaywcjlove** [comment]
@SunPm 我看了一下没有提供纯静态文件，你可以开发模式本地预览文档 [nuxt/nuxtjs.org](https://github.com/nuxt/nuxtjs.org)

**Comment by SunPm** [comment]
@jaywcjlove 好的，谢谢你
