### ISSUE TITLE
kvm 多网卡问题

### ISSUE THREAD

**Issue by JinsYin** [jaywcjlove/handbook#7]
看过 [kvm bridge模式配置](https://github.com/jaywcjlove/handbook/blob/master/CentOS/CentOS7%E5%AE%89%E8%A3%85KVM%E8%99%9A%E6%8B%9F%E6%9C%BA%E8%AF%A6%E8%A7%A3.md#bridge模式配置) 之后，我有一些疑惑想请教一下。

如果我一台物理机有多个网卡，我想到了两种方案：
  1. br0 + eth0, br1 + eth1, br2 + eth2....（有几块网卡就创建几个网桥设备）
  2. br0 <-- eth0/eth1/eth2 （所有网卡都连接到同一个网桥设备上）

哪种方案好呢？方案二最省事，但它能实现负载均衡吗？肯定不希望所有流量都走一个网口。

**Comment by jaywcjlove** [comment]
@JinsYin  之前我的服务器上两个网卡，做的双网卡主备，桥接模式连接虚拟机，当一块网卡宕掉时，另外一块网卡可以自动顶替宕掉的网卡工作，保障网络正常访问。

**Comment by JinsYin** [comment]
@jaywcjlove 好的，依然非常感谢
