### ISSUE TITLE
yum install certbot-nginx -y，试了几种办法还是不行

### ISSUE THREAD

**Issue by happyhuizai** [jaywcjlove/handbook#8]
![-590ed4b4a837a72c](https://user-images.githubusercontent.com/29218617/38244361-06e1cdc0-376d-11e8-9727-e2c3066d58f2.png)

**Comment by a894164233** [comment]
https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx 这是官方网站，选择你的软件和服务器类型，下面有详细的安装步骤。

**Comment by happyhuizai** [comment]
好吧😊

**Comment by jaywcjlove** [comment]
@happyhuizai 我都是编译安装，也挺简单的。

[nginx的所有版本在这里](http://nginx.org/download/)

```bash
yum install -y pcre-devel 
yum -y install gcc make gcc-c++ wget
yum -y install openssl openssl-devel 

wget http://nginx.org/download/nginx-1.13.3.tar.gz
wget http://nginx.org/download/nginx-1.13.7.tar.gz

# 如果没有安装wget
# 下载已编译版本
$ yum install wget

# 解压压缩包
tar zxf nginx-1.13.3.tar.gz
```

然后进入目录编译安装，[configure参数说明](https://github.com/jaywcjlove/nginx-tutorial#%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E)

```bash
cd nginx-1.11.5
./configure
```

如果没有error信息，就可以执行下边的安装了：

```
make
make install
```
